export const mockArtworks = [
  {
    id: '1',
    title: 'Aloe Vera',
    artist: 'Diony Villamor Jr',
    description: 'A study of light and shadow on the fleshy, spined leaves of an aloe vera plant, capturing its resilient spirit.',
    dimensions: '66 in. x 80 in.',
    price: 500,
    imageUrl: 'https://i.imgur.com/U35hBPZ.jpeg',
  },
  {
    id: '2',
    title: 'Courtyard',
    artist: 'Diony Villamor Jr',
    description: 'The quiet solitude of a sun-drenched courtyard, where weathered textures meet vibrant plant life.',
    dimensions: '66 in. x 80 in.',
    price: 500,
    imageUrl: 'https://i.imgur.com/hzsqdnU.jpeg',
  },
  {
    id: '3',
    title: 'Bird’s Nest Fern',
    artist: 'Diony Villamor Jr',
    description: 'An intimate portrait of a Bird’s Nest Fern, with its crinkled fronds unfurling from a central, dark core.',
    dimensions: '66 in. x 80 in.',
    price: 500,
    imageUrl: 'https://i.imgur.com/PZCMO07.jpeg',
  },
    {
    id: '4',
    title: 'Dead Trunk',
    artist: 'Diony Villamor Jr',
    description: 'Finding beauty in decay, this piece focuses on the gnarled and textured surface of a lifeless tree trunk.',
    dimensions: '66 in. x 80 in',
    price: 500,
    imageUrl: 'https://i.imgur.com/ooMgBuu.jpeg',
  },
  {
    id: '5',
    title: 'Taro',
    artist: 'Diony Villamor Jr',
    description: 'The broad, heart-shaped leaves of the taro plant are rendered with dramatic lighting and deep, verdant colors.',
    dimensions: '66 in. x 80 in',
    price: 500,
    imageUrl: 'https://i.imgur.com/EfyQ2OG.jpeg',
  },
  {
    id: '6',
    title: 'Mango',
    artist: 'Diony Villamor Jr',
    description: 'A tribute to the life-giving mango tree, focusing on the interplay between its branches, leaves, and the unseen fruit.',
    dimensions: '66 in. x 80 in.',
    price: 500,
    imageUrl: 'https://i.imgur.com/OCGZjoO.jpeg',
  },
{
    id: '7',
    title: 'Walis Tingting',
    artist: 'Diony Villamor Jr',
    description: 'An unconventional subject, the humble Filipino broom is elevated to an object of textural and compositional interest.',
    dimensions: '66 in. x 80 in.',
    price: 500,
    imageUrl: 'https://i.imgur.com/IvFpyeG.jpeg',
  },
  {
    id: '8',
    title: 'Aloe Vera Pots',
    artist: 'Diony Villamor Jr',
    description: 'A collection of potted aloe vera plants, exploring themes of domesticity, growth, and contained nature.',
    dimensions: '66 in. x 80 in.',
    price: 500,
    imageUrl: 'https://i.imgur.com/WDOxaza.jpeg',
  },
{
    id: '9',
    title: 'Gripo',
    artist: 'Diony Villamor Jr',
    description: 'A hyper-realistic depiction of a common faucet, highlighting the reflections and metallic sheen of its surface.',
    dimensions: '66 in. x 80 in.',
    price: 500,
    imageUrl: 'https://i.imgur.com/Xm3DXQ3.jpeg',
  },

  {
    id: '10',
    title: 'Life Thru Cracks',
    artist: 'Diony Villamor Jr',
    description: 'A powerful metaphor for resilience, as a small plant emerges defiantly from a crack in the pavement.',
    dimensions: '66 in. x 80 in.',
    price: 500,
    imageUrl: 'https://i.imgur.com/aD9KH1z.jpeg',
  },
{
    id: '11',
    title: 'Jesse',
    artist: 'Diony Villamor Jr',
    description: 'A striking portrait that captures a moment of introspection and quiet strength in its subject, Jesse.',
    dimensions: '66 in. x 80 in.',
    price: 500,
    imageUrl: 'https://i.imgur.com/5RZWhB3.jpeg',
  },
  {
    id: '12',
    title: 'Diony',
    artist: 'Diony Villamor Jr',
    description: 'A self-portrait of the artist, offering a candid and vulnerable look at the creator behind the canvas.',
    dimensions: '66 in. x 80 in.',
    price: 500,
    imageUrl: 'https://i.imgur.com/feRPvRt.jpeg',
  }
];